apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - name: http-web
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: spring-boot-app
